apiVersion: v1 
kind: Service 
metadata:
  name: eplant-shopping-service 
spec:
  selector:
    app: eplant-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 
      nodePort: 30124
  type: NodePort