apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
  namespace: multi-container
spec:
  containers:
  - name: my-container
    image: busybox
    command: ['sh', '-c']
    args: ["while true; do echo 'App is running...'; sleep 5; done"]
    
    env:
      - name: MY_NAME
        value: "Tirumala Rao"

  initContainers:
    - name: my-init-cont-1 
      image: busybox 
      command: ['sh','-c']
      args: ['until nslookup  myservice.default.svc.cluster.local; do echo waiting for service to start;sleep 3; done']



