apiVersion: v1
kind: Service
metadata:
  name: eplant-svc-1
  namespace: dev
spec:
  selector:
    app: eks-eplant
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80        # External port
      targetPort: 80  # Container port
