apiVersion: v1 
kind: Secret 
metadata: 
  name: mongodb-cred-secret 
  namespace: mongodb-ns 

type: Opaque
data: 
   MONGO_ROOT_USERNAME: YWRtaW4=       # username is encoded using (echo -n "Your_username" | base64)
   MONGO_ROOT_PASSWORD: cGFzc3dvcmQ=   # password is encoded using (echo -n "Your_password" | base64)

