
apiVersion: v1
kind: Pod
metadata:
  name: stress-test
  namespace: resource-limits
spec:
  containers:
  - name: stress
    image: progrium/stress
    command: ["stress"]
    args: ["--cpu", "2", "--vm", "1", "--vm-bytes", "200M", "--timeout", "300s"]
    resources:
      requests:
        memory: "128Mi"
        cpu: "500m"
      limits:
        memory: "600Mi"
        cpu: "1"



#To enable the Metrics Server on a MicroK8s cluster, run the following command:
  # microk8s enable metrics-server


#After enabling, you can check CPU and memory usage using:

  #   microk8s kubectl top nodes
  #  microk8s kubectl top pods --all-namespaces '''