apiVersion: apps/v1
kind: StatefulSet
metadata:
   name:  mysql-stateful
   namespace: state-ns
spec:
  serviceName: my-sql-svc 
  replicas: 3 
  selector:
     matchLabels:
         app: mysql-stateful 

  template:
    metadata:
      labels:
        app: mysql-stateful

    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "password123"

          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql

  volumeClaimTemplates:
    - metadata: 
        name: mysql-storage

      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
      

    