apiVersion: v1 
kind: Service 
metadata:
  name: my-sql-svc 
  namespace: state-ns

spec:
  type: ClusterIP
  selector:
    app: mysql-stateful
  

  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30036  
  clusterIP: None