apiVersion: v1
kind: Pod
metadata:
  name: load-generator
  namespace: hpa
spec:
  containers:
  - name: busybox
    image: busybox
    command:
    - /bin/sh
    - -c
    - >
      while true; do
        wget -q -O- http://hpa-service;
      done
