apiVersion: apps/v1
kind: DaemonSet
metadata: 
   name:  nginx
   namespace: daemonset-ns
spec: 
  selector:
    matchLabels:
       app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
         - name: daemon-nginx
           image: nginx
           ports:
             - containerPort: 80
      
