apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replica 
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: nginx-app-replica 
  template:
    metadata:
      labels:
        app: nginx-app-replica 
    spec:
      containers:
        - name: nginx-cr 
          image: nginx:latest 
          ports:
            - containerPort: 80 
               