apiVersion: v1
kind: Service
metadata:
  name: my-nginx-lb-service
  namespace: test 
spec:
  selector:
    app: nginx-deploy
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80        # External port
      targetPort: 80  # Container port
